In [1]:
import plotly.express as px
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

Post the following to the discussion board:

Attach your visualization.

Explain the method you used to create the visualization.

Share what library you used.

Describe the results you found and what they tell you about the dataset you chose.

In [2]:
df = pd.read_csv('data/allvisits.csv')

In [3]:
df.describe()

       County FIPS          Year          Week
count          0.0  26240.000000  26240.000000
mean           NaN   2022.565625     26.234375
std            NaN      1.763041     15.294431
min            NaN   2020.000000      1.000000
25%            NaN   2021.000000     13.000000
50%            NaN   2023.000000     26.000000
75%            NaN   2024.000000     39.250000
max            NaN   2026.000000     53.000000

In [4]:
"""
df[(df["Entity"] == "China") & (df["Year"] == 2017)]
# GDP of China in 2017 using query
df.query('Entity == "China" and Year == 2017')

"""

'\ndf[(df["Entity"] == "China") & (df["Year"] == 2017)]\n# GDP of China in 2017 using query\ndf.query(\'Entity == "China" and Year == 2017\')\n\n'

In [5]:
df.columns

Index(['Report Date', 'Week Ending Date', 'Health Region', 'Health District',
       'Facility Type', 'County FIPS', 'Year', 'Week',
       'Percent of ED Visits Covid', 'Percent of ED Visits Influenza',
       'Percent of ED Visits RSV', 'Percent of ED Visits Combined',
       'Diagnosed Covid Count', 'Diagnosed Influenza Count',
       'Diagnosed RSV Count', 'Combined Respiratory Viruses Count'],
      dtype='str')

In [6]:
# +

df= df[df["Health Region"] != "Out of State"]

In [7]:
years = df["Year"].unique()
years

array([2025, 2021, 2020, 2022, 2023, 2024, 2026])

In [8]:
districts = df["Health District"].unique()
districts

<ArrowStringArray>
[       'Central Region',                'Crater',               'Henrico',
              'Piedmont',             'Southside',          'Chesterfield',
          'Chickahominy',              'Richmond',            'Chesapeake',
        'Eastern Region',         'Eastern Shore',               'Hampton',
               'Norfolk',             'Peninsula',            'Portsmouth',
          'Three Rivers',        'Virginia Beach',     'Western Tidewater',
             'Arlington',               'Fairfax',               'Loudoun',
            'Alexandria',       'Northern Region',        'Prince William',
    'Central Shenandoah',          'Lord Fairfax',            'Blue Ridge',
          'Rappahannock',  'Rappahannock Rapidan',      'Northwest Region',
             'Alleghany',      'Central Virginia',    'Cumberland Plateau',
             'Lenowisco',          'Mount Rogers',             'New River',
 'Pittsylvania-Danville',      'Southwest Region',         'West Piedmont',
               'Roanoke']
Length: 40, dtype: str

In [9]:
region = df["Health Region"].unique()
region

<ArrowStringArray>
[  'Central Region',   'Eastern Region',  'Northern Region',
 'Northwest Region', 'Southwest Region']
Length: 5, dtype: str

In [10]:
#df_inf_count = df_va[df_va["Diagnosed Influenza Count"].apply(lambda x: x.isnumeric())]
df["FlueCount"] = pd.to_numeric(df["Diagnosed Influenza Count"], errors='coerce')
# Or simply:
# df['your_numeric_column'] = df['your_numeric_column'].astype(float)

In [11]:
df = df.dropna(subset="FlueCount")

In [12]:
df[df["FlueCount"].isna()]

Empty DataFrame
Columns: [Report Date, Week Ending Date, Health Region, Health District, Facility Type, County FIPS, Year, Week, Percent of ED Visits Covid, Percent of ED Visits Influenza, Percent of ED Visits RSV, Percent of ED Visits Combined, Diagnosed Covid Count, Diagnosed Influenza Count, Diagnosed RSV Count, Combined Respiratory Viruses Count, FlueCount]
Index: []

In [13]:
df_2025 = df[df["Year"] == 2025]
 
len(df_2025)

3230

In [14]:
df_2025_wk = df_2025.groupby(['Week Ending Date', 'Health Region'], as_index=False)['FlueCount'].sum()

In [15]:
df_2025_wk

    Week Ending Date     Health Region  FlueCount
0         2025-01-04    Central Region     3942.0
1         2025-01-04    Eastern Region     3449.0
2         2025-01-04   Northern Region     2788.0
3         2025-01-04  Northwest Region     1778.0
4         2025-01-04  Southwest Region     1236.0
..               ...               ...        ...
260       2026-01-03    Central Region     5324.0
261       2026-01-03    Eastern Region     7376.0
262       2026-01-03   Northern Region     6100.0
263       2026-01-03  Northwest Region     3936.0
264       2026-01-03  Southwest Region     2966.0

[265 rows x 3 columns]

In [17]:
fig = px.line(df_2025_wk, x="Week Ending Date", y="FlueCount", color="Health Region")
fig.write_image('images/flu_regions_2025.png')