## Required Assignment 2.3: Computing the Sample Covariance Matrix

**Expected Time: 45 Minutes**

**Total Points: 20**

This activity focuses on using covariance and correlation to understand the strength of relationships between two quantitative variables.  Also, you will use a heatmap to visualize these relationships.  Finally, you identify situations where correlation is not an appropriate measure based on the assumption of a linear variable.

## Index:

- [Problem 1](#Problem-1:-Calculating-Covariance)
- [Problem 2](#Problem-2:-Calculating-Correlation)
- [Problem 3](#Problem-3:-Heatmap-of-Covariance)
- [Problem 4](#Problem-4:-Heatmap-of-Correlation)

### Covariance and Correlation

In probability theory and statistics, the mathematical concepts of covariance and correlation are very similar. Both describe the degree to which two random variables or sets of random variables tend to deviate from their expected values in similar ways.

If X and Y are two random variables, with means (expected values)  $\mu_X$ and  $\mu_Y$ and standard deviations  $σ_X$ and  $σ_Y$, respectively, then their covariance and correlation are as follows:

Covariance $$\text{cov}_{XY}=\sigma_{XY}=E[(X-\mu_{X})\,(Y-\mu_{Y})]$$

Correlation $$\text{corr}_{XY} = \rho_{XY} = E[(X - \mu_X)(Y - \mu_Y)]/(\sigma_X \sigma_Y)$$

so that

$$\rho_{XY}=\sigma_{XY}/(\sigma_{X} \sigma_{Y})$$


where E is the expected value operator. Notably, correlation is dimensionless, while covariance is in units obtained by multiplying the units of the two variables. --[source](https://en.wikipedia.org/wiki/Covariance_and_correlation)

#### Dataset: Penguins

Our sample dataset comes from the `seaborn` visualization library and contains measurements of penguins of different species located on different islands.  Below, we load the data and display the first few rows and datatype information.

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
penguin_df = pd.read_csv('data/penguins.csv')

In [3]:
penguin_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    str
 1   island             333 non-null    str
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 24.1 KB

In [4]:
penguin_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

[Back to top](#Index:) 

### Problem 1: Calculating Covariance

**4 Points**

Pandas DataFrame's have a built in `.cov()` method that will return the covariance between each numeric feature.

Use the `.cov()` method on `penguin_df` to create the covariance matrix.  Assign your solution to the variable `penguins_cov` below.

In [6]:
### GRADED

penguins_cov = ''

### BEGIN SOLUTION
penguins_cov = penguin_df.select_dtypes(include='number').cov()
### END SOLUTION
penguins_cov

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
bill_length_mm,29.906333,-2.462091,50.058195,2595.623304
bill_depth_mm,-2.462091,3.877888,-15.947248,-748.456122
flipper_length_mm,50.058195,-15.947248,196.441677,9852.191649
body_mass_g,2595.623304,-748.456122,9852.191649,648372.487699

[Back to top](#Index:) 

### Problem 2: Calculating Correlation

**4 Points**

Similarly, pandas DataFrames have a built-in `.corr()` method that computes the correlation matrix for numerical columns.  

Use the `.corr()` method on `penguin_df` and assign your results to the variable `penguins_corr`.

In [7]:
### GRADED

penguins_corr = ''

### BEGIN SOLUTION
penguins_corr = penguin_df.select_dtypes(include='number').corr()
penguins_corr
### END SOLUTION

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
bill_length_mm,1.000000,-0.228626,0.653096,0.589451
bill_depth_mm,-0.228626,1.000000,-0.577792,-0.472016
flipper_length_mm,0.653096,-0.577792,1.000000,0.872979
body_mass_g,0.589451,-0.472016,0.872979,1.000000

[Back to top](#Index:) 

### Heatmap of Correlation 

The code cell below displays a heatmap of the correlation matrix for the `penguin_df` DataFrame. Run the code cell below.

In [ ]:
numeric_df = penguin_df.select_dtypes(include='number')

sns.heatmap(numeric_df.corr(), annot=True)

[Back to top](#Index:) 

### Problem 3: Strongest Positive Correlation

**8 Points**

Which two features have the strongest positive correlation?  Enter your answer as a list of strings using the exact column names to `highest_pos_corr` below.

In [ ]:
### GRADED

highest_pos_corr = ''

### BEGIN SOLUTION
highest_pos_corr = ['body_mass_g', 'flipper_length_mm']
### END SOLUTION

[Back to top](#Index:) 

### Problem 4: Interpreting negative correlation

**4 Points**

The correlation between `body_mass_g` and `bill_depth_mm` reads -0.47.  Complete the following sentence that interprets this correlation.

```
As body mass increases bill depth ___________
```

Assign your solution as a string -- either `increases`, `decreases`, or `neither` to `ans_4` below.

In [ ]:
### GRADED

ans_4 = ''

### BEGIN SOLUTION
ans_4 = 'decreases'
### END SOLUTION