### Required Assignment 4.1: Complex Joins on Datasets

**Expected Time: 60 Minutes**

**Total Points: 10**

![](images/kiva.png)

This assignment focuses on using pandas `merge` to answer questions using multiple data sources.  Here, you will combine data and use many of the earlier `pandas` methods together with the `merge` function to extract insights from our data source.  The data comes from the Kiva loan provider organization and was part of a Kaggle Data Science for Good contest [here](https://www.kaggle.com/kiva/data-science-for-good-kiva-crowdfunding).

#### Index:

- [Problem 1](#Problem-1)
- [Problem 2](#Problem-2)
- [Problem 3](#Problem-3)
- [Problem 4](#Problem-4)
- [Problem 5](#Problem-5)

### The Data

Kiva allows users to fund loans to small organizations around the world.  The four datasets contain a subset of the data provided on Kaggle and describe information on the individual loan when it was given, where the borrowers were located, and what the loans were being used for.  Below, the data is loaded into four DataFrames, and the first two rows of each are displayed.  Note the shared `id` column across all four datasets.

In [1]:
import pandas as pd

In [2]:
crowdsource = pd.read_csv('data/kiva/crowdsource.csv')
crowdsource.head(2)

        id                posted_time                funded_time  lender_count
0   658776  2014-01-17 21:21:10+00:00  2014-02-05 17:57:55+00:00            33
1  1314847  2017-06-07 02:02:41+00:00  2017-06-21 17:10:38+00:00             9

In [3]:
demographics = pd.read_csv('data/kiva/demographics.csv')
demographics.head(2)

        id      country                 region borrower_genders
0   658776  El Salvador      Ciudad El Triunfo             male
1  1314847  Philippines  Bais, Negros Oriental           female

In [4]:
financials = pd.read_csv('data/kiva/financials.csv')
financials.head(2)

        id  funded_amount currency  term_in_months
0   658776         1000.0      USD            20.0
1  1314847          225.0      PHP            13.0

In [5]:
use = pd.read_csv('data/kiva/use.csv')
use.head(2)

,id,activity,sector,use
0,658776,Vehicle,Personal Use,to purchase a motorcycle in order to travel fr...
1,1314847,Pigs,Agriculture,to buy feed and other supplies like vitamins t...

In [6]:
demographics[demographics["country"] == "Kenya"]

           id country     region                  borrower_genders
5      766484   Kenya  Msambweni                            female
19    1191351   Kenya   Kerugoya                            female
20    1049704   Kenya     Kitale                            female
52    1081411   Kenya        NaN                            female
59     876662   Kenya      Kisii                              male
...       ...     ...        ...                               ...
9965   825773   Kenya     Nakuru                    female, female
9972  1305189   Kenya      Thika                              male
9988   771844   Kenya   Machakos                            female
9992   992118   Kenya       Molo                              male
9996   873525   Kenya   Machakos  male, male, female, female, male

[1139 rows x 4 columns]

In [7]:
dk = demographics.query("country == 'Kenya'")

In [8]:
df1 = pd.merge(dk, financials, how="inner", on="id")

In [9]:
df1

,id,country,region,borrower_genders,funded_amount,currency,term_in_months
0,766484,Kenya,Msambweni,female,350.0,KES,13.0
1,1191351,Kenya,Kerugoya,female,200.0,KES,14.0
2,1049704,Kenya,Kitale,female,375.0,KES,14.0
3,1081411,Kenya,NaN,female,125.0,KES,3.0
4,876662,Kenya,Kisii,male,275.0,KES,12.0
...,...,...,...,...,...,...,...
1134,825773,Kenya,Nakuru,"female, female",225.0,KES,11.0
1135,1305189,Kenya,Thika,male,125.0,KES,14.0
1136,771844,Kenya,Machakos,female,225.0,KES,11.0
1137,992118,Kenya,Molo,male,100.0,KES,8.0
1138,873525,Kenya,Machakos,"male, male, female, female, male",375.0,KES,14.0

In [10]:
meanfunded = df1[['funded_amount']].mean()

In [11]:

meanfunded.values[0]

np.float64(443.4723441615452)

[Back to top](#Index:) 

### Problem 1

#### Kenyan Loan Amounts

**5 Points**


Use the `demographics` and `financials` data to determine the average loan amount for the country `Kenya`.  

Note that the average loan amount in each country can be calculated by computing the mean of the `funded_amount` column.


Save your response as a float to `ans1` below.

In [12]:
### GRADED

ans1 = None

### BEGIN SOLUTION
ans1 = pd.merge(demographics.loc[demographics['country'] == 'Kenya'], financials, on = 'id')[['funded_amount']].mean().values[0]
type(ans1)
### END SOLUTION

# Answer check
print(ans1)
print(type(ans1))

443.4723441615452
<class 'numpy.float64'>

[Back to top](#Index:) 

### Problem 2

### El Salvador Top Sector

**5 Points**

Use the `demographics` and `use` datasets to determine the sector of work that received the most loans in `El Salvador`.  

Note that the  the sector of work in each country can be calculated by using `value_counts()` on the `sector` column.


Assign your result as a string to `ans2` below.

In [13]:
demographics.head(2)

        id      country                 region borrower_genders
0   658776  El Salvador      Ciudad El Triunfo             male
1  1314847  Philippines  Bais, Negros Oriental           female

In [14]:
use.head(2)

,id,activity,sector,use
0,658776,Vehicle,Personal Use,to purchase a motorcycle in order to travel fr...
1,1314847,Pigs,Agriculture,to buy feed and other supplies like vitamins t...

In [15]:
df1 = pd.merge(left=demographics, right=use, how='inner', on='id')

In [16]:
df1.head(3)

,id,country,region,borrower_genders,activity,sector,use
0,658776,El Salvador,Ciudad El Triunfo,male,Vehicle,Personal Use,to purchase a motorcycle in order to travel fr...
1,1314847,Philippines,"Bais, Negros Oriental",female,Pigs,Agriculture,to buy feed and other supplies like vitamins t...
2,863063,Peru,Huarochiri,"female, female, female, female, female, female...",Bookstore,Retail,"to buy notebooks, pencils, and pens."

In [17]:
df1['sector'].unique()

<ArrowStringArray>
[  'Personal Use',    'Agriculture',         'Retail',       'Services',
           'Food',       'Clothing',      'Education',   'Construction',
        'Housing', 'Transportation',           'Arts',         'Health',
  'Manufacturing',  'Entertainment',      'Wholesale']
Length: 15, dtype: str

In [18]:
df2 = df1.groupby('sector')["sector"].value_counts()

In [19]:
df2 = df2.reset_index()

In [20]:
ans = df2[df2['count'] == df2['count'].max()]

In [21]:
ans

        sector  count
0  Agriculture   2681

In [22]:
ans.iloc[0]['sector']

'Agriculture'

In [23]:
### GRADED

ans2 = None

### BEGIN SOLUTION
ans2 = pd.merge(demographics.loc[demographics['country'] == 'El Salvador'], use, on = 'id')['sector'].value_counts().index[0]
type(ans2)
### END SOLUTION

# Answer check
print(ans2)
print(type(ans2))

Agriculture
<class 'str'>

### Problem 3

#### Pakistan Loans in Agriculture

**5 Points**


Merge the DataFrames `use` and `demographics` on `id`. Assign your result to `p1`.

Merge the DataFrames `p1` and `financials` on `id`. Assign your result to `a`.

Use `loc` on the `a` DataFrame to select the rows in which `country` is equal to `Pakistan`. Assogn your result to `b`.


Determine the total amount of loans (`funded_amount`) for `Agriculture` in Pakistan.  Assign your results as a float to `ans3` below.

In [24]:
### GRADED

ans3 = None

### BEGIN SOLUTION
p1 = pd.merge(use, demographics, on = 'id')
a = pd.merge(p1, financials, on = 'id')
#b = a.query("country == 'Pakistan'")
b = a.loc[a['country'] == 'Pakistan']
ans3 = b.loc[b['sector'] == 'Agriculture'][['funded_amount']].sum().values[0]

### END SOLUTION

# Answer check
print(ans3)
print(type(ans3))

30900.0
<class 'numpy.float64'>

[Back to top](#Index:) 

### Problem 4

#### Top Total Loan Sector

**5 Points**

Merge the `financials` and `use` DataFrames on `id`. To this, chain a `groupby()` operation on `sector` and use a double square bracket notation to select the column `funded_amount`.



What sector received the most total dollars in funding?  Assign your response as a string to `ans4` below.

In [25]:
### GRADED

ans4 = None

### BEGIN SOLUTION
ans4 = pd.merge(financials, use, on = 'id').groupby('sector')[['funded_amount']].sum().sort_values(by = 'funded_amount', ascending = False).index[0]
### END SOLUTION

# Answer check
print(ans4)
print(type(ans4))

Agriculture
<class 'str'>

[Back to top](#Index:) 

### Problem 5

#### Top Loan by Lender Amount

**5 Points**

Merge the DataFrames `financials` and `use` on `id`. Assign your result to `a`.

Merge the DataFrames `a` and `crowdsource` on `id`. Assign your result to `b`.

In the `b` DataFrame, create a new column `ratio`. To this column assign the ratio of the columns `funded_amount` and `lender_count` of the `b` DataFrame.


Determine which loan sector has the highest ratio of currency to lender amount. Assign the sector with the highest ratio as a string to `ans5` below.

In [26]:
### GRADED

ans5 = None

### BEGIN SOLUTION
a = pd.merge(financials, use, on = 'id')
b = pd.merge(a, crowdsource, on = 'id')
b['ratio'] = b['funded_amount']/b['lender_count']
ans5 = b.groupby('sector')['ratio'].max().idxmax()
### END SOLUTION

# Answer check
print(ans5)
print(type(ans5))

Retail
<class 'str'>

In [27]:
crowdsource_ = pd.read_csv('data/kiva/crowdsource.csv')
demographics_ = pd.read_csv('data/kiva/demographics.csv')
financials_ = pd.read_csv('data/kiva/financials.csv')
use_ = pd.read_csv('data/kiva/use.csv')
a_ = pd.merge(financials_, use_, on = 'id')
b_ = pd.merge(a_, crowdsource, on = 'id')
b_['ratio'] = b_['funded_amount']/b_['lender_count']
ans5_ = b_.groupby('sector')['ratio'].max().idxmax()

In [28]:
ans5_

'Retail'